Improve OCR
crow-translate/crow-translate pull request #232
Opened 2021-01-06 11:13 UTC by LiteracyFanatic

The first commit makes tesseract read from a config file. The following parameters are of particular interest for CJK languages, especially when written vertically. Unfortunately automatic script and orientation detection is only supported by the legacy engine. The newer LSTM models usually give better results but require manually specifying the orientation.

```ini
# Tells tesseract whether the script is horizontal (6) or vertical (5)
tessedit_pageseg_mode
# Don't add spaces between characters
preserve_interword_spaces
# toggling these options on or off may improve the output in some circumstances
paragraph_text_based
textord_old_baselines
lstm_use_matrix
```

I've been experimenting with the in development tesseract v5 on my system, so the second commit makes crow compile with it. The v5 API is still very much a moving target, so you might prefer to wait for a stable release first. That being said, it isn't too bad since crowing is only using a small subset of the API.

Thoughts?

2021-01-06 13:19 UTC, Shatur95 commented
Thanks! I like the idea to support upcoming tesseract v5, but not sure about user experience with a separate configuration file. Can we set configuration parameters just in settings?

2021-01-09 03:13 UTC, LiteracyFanatic commented
>  Can we set configuration parameters just in settings?

That's certainly a valid option too. Having the options right in the settings dialog saves users from needing to know what tesseract is and looking up its config options. On the other hand, tesseract has a lot of parameters (over 600). I'm sure the subset of those that actually sees regular use in the wild is much smaller, but potentially still more than we want to shove in the settings dialog verbatim. I'll also note that typical use cases often involve using multiple config files to switch a number of parameters at once- basically setting up profiles for different types of text.

There are definitely some options which I think would be worth having exposed directly, `tessedit_pageseg_mode` and `preserve_interword_spaces` for example. I'd still like the ability to pass arbitrary parameters though. Perhaps we can add a setting group called tesseract and iterate over its values with `QSettings::childKeys()` when performing OCR. `TessBaseAPI::SetVariable()` excepts arbitrary strings, so we wouldn't have to hard code all the values. That way users could edit the most common parameters through the UI, but still be able to pass advanced options by adding them to `Crow Translate.conf` directly.

2021-01-09 09:12 UTC, Shatur95 commented
> I'll also note that typical use cases often involve using multiple config files to switch a number of parameters at once- basically setting up profiles for different types of text.

Got it. Let's merge this as is for now.

> That's certainly a valid option too. Having the options right in the settings dialog saves users from needing to know what tesseract is and looking up its config options. On the other hand, tesseract has a lot of parameters (over 600).

Yes, I understand. I wanted to suggest just being able to set these variables in the settings. Let's say `QLineEdit`, where you can write a new variable name, and next to it is an add and remove button. And at the bottom is `QListWidget` with variables. After saving setting, the variables will be written to the specified file. If no file was specified, the settings will be written to the Crow parameter file as a list. What do you think about this functionality?

>  Perhaps we can add a setting group called tesseract and iterate over its values with QSettings::childKeys() when performing OCR. 

It would be nice, but `QSettings` not suited for storing only variables. You will need to provide a key. But just storing `QStringList` is a valid option.

2021-01-09 09:18 UTC, Shatur95 requested changes
Just two very minor suggestions before merge.

2021-01-09 09:18 UTC, Shatur95 commented on src/settings/appsettings.cpp
> +    return tesseractConfig.toLocal8Bit();
I think it should be empty by default since currently user need to create edit it manually.

```suggestion
    return {};
```

2021-01-09 09:18 UTC, Shatur95 commented on src/settings/settingsdialog.cpp
> +    const QString file = QFileDialog::getOpenFileName(this, tr("Select OCR config path"), path);
I usually prefer to pass small thing directly, so just for consistency:
```suggestion
    const QString file = QFileDialog::getOpenFileName(this, tr("Select OCR config path"), ui->ocrConfigPathEdit->text());
```

2021-01-09 09:22 UTC, Shatur95 commented on src/ocr/ocr.cpp
> +        m_tesseract.ReadConfigFile(qPrintable(AppSettings().ocrConfigPath()));
I think that you can just set it directly. BTW, shouldn't we check if the file is empty?
```suggestion
        m_tesseract.ReadConfigFile(AppSettings().ocrConfigPath());
```

2021-01-09 10:52 UTC, Shatur95 commented
No, I didn't mean to export some options separately. This will unnecessarily complicate the code. And I didn't mean to add it all in one PR. Remember for the future - one PR - one change.

2021-01-09 11:03 UTC, merged

2021-01-09 11:06 UTC, Shatur95 commented
I left only fixes for tesseract v5 + minor refactoring to merge things right now.
Let's discuss the implementation of settings first. You will able to cherry-pick your changes from your local branch to a new PR. I will create an issue for it, give me a five minutes.

2021-01-09 11:15 UTC, LiteracyFanatic commented
Thanks for the feedback. Yes, it got rather messy while I was experimenting. I had it all in one branch because I can't build to test the other changes without the v5 commit (should probably build a copy of v4 from source). I was planning to split it up once I got things working.

2021-01-09 11:25 UTC, Shatur95 commented
> I had it all in one branch because I can't build to test the other changes without the v5 commit (should probably build a copy of v4 from source).

Oh, got it!

Let's discuss the implementation first in #233.