Add "Search on Forvo" action to source text context menu
crow-translate/crow-translate pull request #295
Opened 2021-04-16 17:50 UTC by flyvint

i fixed your suggestions from PR #294

ps: i created new PR because github closed previous #294, when i moved my commits to branch and updated master from your repo :(

2021-04-16 20:17 UTC, Shatur95 requested changes
> ps: i created new PR because github closed previous #294, when i moved my commits to branch and updated master from your repo :(

No problem :)

2021-04-16 20:17 UTC, Shatur95 commented on src/mainwindow.cpp
> +}
I meant to move this inside `SourceTextEdit` to connect `&QAction::triggered` directly to this method . Sorry if I was unclear :)

BTW, maybe it is worth making the same menu for translation? I think this functionality will be useful.
If you agree with my idea, I will try to move the functionality to a separate class myself to call it in both edits.

2021-04-18 17:29 UTC, flyvint commented on src/mainwindow.cpp
> +}
:) ок

2021-04-18 17:35 UTC, flyvint commented on src/mainwindow.cpp
> +}
about menu for translation: it would great

2021-04-18 22:19 UTC, merged